---
homebrew_taps:
  - wallix/awless

homebrew_installed_packages:
  - git
  - mysql
  - tree
  - zsh
  - zsh-completions
  - tmux
  - { name: "vim", install_options: "with-override-system-vi" }
  - the_silver_searcher
  - antigen
  - htop
  - imagemagick
  - tesseract
  - gawk
  - bindfs
  - openvpn
  - redis
  - node
  - awless
  - terraform
  - go
  - heroku/brew/heroku
  - python
  - python3
  - yarn
  - tig

homebrew_cask_apps:
  - virtualbox
  - vagrant
  - chefdk
  - osxfuse
  - tunnelblick
  - paw
  - slack
  - macdown

mas_installed_apps:
  - { id: 531349534, name: "Tadam (2.0.1)" }
  - { id: 957734279, name: "TogglDesktop (7.4.58)" }
  - { id: 585829637, name: "Todoist (7.0.8)" }
  - { id: 425955336, name: "Skitch (2.8)" }

pip_install_packages:
  - glances
  - mdv

