---
homebrew_installed_packages:
  - git
  - mysql
  - tree
  - zsh
  - zsh-completions
  - tmux
  - { name: "vim", install_options: "with-override-system-vi" }
  - the_silver_searcher
  - antigen
  - htop
  - imagemagick
  - gawk

homebrew_cask_apps:
  - virtualbox
  - vagrant
  - chefdk

pip_install_packages:
  - glances

